# GitHub Actions workflow for building Docker image and deploying to Fly.io
# Reference: https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
# This workflow will run on every push to the 'main' branch
name: Fly Deploy

# Define when the workflow should trigger
on:
  push:
    branches:
      - main

# Define the jobs to be executed
jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Bun environment
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run unit tests with coverage
      - name: Run unit tests with coverage
        run: bun run test:cov

      # Run E2E tests
      - name: Run E2E tests
        run: bun run test:e2e

  # Job to build and push Docker image to Docker Hub
  docker:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu runner
    needs: test  # Only run after tests pass
    steps:
      # Set up QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Log in to Docker Hub using credentials from GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Your Docker Hub username
          username: cecep31
          # Docker Hub access token stored in GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Push the image after building
          push: true
          # Tag the image with 'latest'
          tags: cecep31/nestbackend:latest
  # Job to deploy the application to Fly.io
  deploy:
    # This job will only run after the 'docker' job completes successfully
    needs: docker
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    # Ensure only one deployment runs at a time to prevent conflicts
    concurrency: deploy-group
    
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up Fly.io CLI (flyctl)
      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      # Deploy the application to Fly.io using the '--remote-only' flag
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          # Fly.io API token stored in GitHub Secrets for authentication
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
